travis:
  secure:
    BINSTAR_TOKEN: JDW5ceHEyqoXfL0WT1DKffUXUNXWKngwhOmXy8aJOIjB0QQwtWBN0pwwkM+QAclrk0h6e5ToF/dzcyMk9lUZ9nqHhiqxfGXFTWEDn75ZEhtGo6fxxxWFU6rYo0HU03RiGilNDYYdoEG3aIjYweJ03zg9lo6K8oci+wflwZr/BY6Md4quTGQCqdGTz7j9IpfP4V6vZi7hqnR0XfyrZLD1qae50oWXytVN3urEsocLVVtrkBzP3+mhjP1DYHdLTRYrZZUusYuJC+SBuJrBAqHclExLIm+DbnZKNP5Wwm3M8eXod9NSUcaVa8ZOfqVkI55adVXgGxcZq/lSjpXWDNhcKeMbu/+RUIaWaN4h/sndaAbbnWuWOQG8CBNxd+tUDEogdxv9aRtSiwf1z0kTWkHrZn7uM+6tphdQX/nVYwzyKimgnq4fuybiW3yMlOuW8uVNr+mvFljTBP70kfjlBQd8CKLNzooV06YfEdJ1eWrIhAso0oBSQAt89PdR3/mXqX7YYPUEqcf2jXqZpmM6MywFMk1uIvkIlOlygCbElzhlkr/3w75GPCkvViKYpBlxKuV2ODVtN0WgkAu696R8ZRoVzoEwkNiQmKmy5XWZfiIKnmnCSo3lid6X12mNWj1omV3ULc1JzZR5Fvyb/pTOKqXxnWrsHfimO+TaBkIjLAh3ZWE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
